config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shopping_lists

  resources :foods, only: %i[index new create show destroy]
  resources :users, only: %i[index new create show destroy]
  resources :recipes, only: %i[index new create show destroy] do
    resources :recipes_foods, only: %i[new create]
  end

  root 'users#index'
  get '/public_recipes', to: 'public_recipes#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipes_foods
  has_many :foods, through: :recipes_foods
  validates :name, presence: true
  validates :user, presence: true
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :description, presence: true
  validates :public, inclusion: { in: [true, false] }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.includes(:user).where(id: params[:id]).first
    @recipe_foods = RecipesFood.includes(:food, :recipe).where(recipe_id: params[:id])
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <div class="d-flex flex-column align-items-center">
 <div class= "d-flex flex-column align-items-center w-75 mb-3">
   
    <%= form.text_field :name, Placeholder: "Name", class: "form-control w-75 mb-4" %>


    <div class="ml-auto">
    <%= form.check_box :public, class:"form-check-input", id:"flexSwitchCheckChecked"  %>
    <%= form.label :public %>
    
    </div>



 
    <%= form.text_field :description, Placeholder: "Description", class: "form-control w-75 mb-4" %>


 
     
      <%= form.text_field :preparation_time, Placeholder: "Preparation Time", class: "form-control w-75 mb-4" %>
   
      <%= form.text_field :cooking_time, Placeholder: "Cooking Time", class: "form-control w-75 mb-4" %>
  


    <%= form.submit class: "btn btn-primary" %>


    </div>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <div>
    <h5></h5>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <div class="d-flex justify-content-between">
      <div>
        <div>
          <h5><%= recipe.name %></h5>
        </div>
        <div class="d-flex">
          <button type="button" class="btn btn-primary">
            <%= link_to 'Details', recipe_path(recipe), method: :get, class: "nav-link" %>
          </button>
          <% if can? :destroy, recipe %>
            <div>
              <%= button_to 'Remove', recipe_path(recipe), method: :delete, class: "btn btn-danger" %>
            </div>
          <% end %>
        </div>
      </div>
      <div>
        <p><%= recipe.description %></p>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "New recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<h1 class="text-center">New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path, class: "bottom-link" %>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div><%= @recipe.name %></div>
  <div>
    <div>
      <h5>Preparation time : <%= @recipe.preparation_time %></h5>
    </div>
    <div>
      <h5>Public : <%= @recipe.public %></h5>
    </div>
  </div>
  <div>
    <h5>Cooking time : <%= @recipe.cooking_time %></h5>
  </div>
  <div>
    <div>
      <%= link_to 'Generate shopping list', shopping_lists_path, class: "btn btn-primary" %>
    </div>
    <% if @recipe.user == current_user %>
      <div class="add_ing">
        <%= link_to 'Add ingredient', new_recipe_recipes_food_path(@recipe.id), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <th scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @recipe_foods.each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
        <td>$<%= recipe_food.quantity * recipe_food.food.price %></td>
        <td>
          <div>
            <div>
              <%= button_to 'Modify', method: :put, class: "btn btn-primary" %>
            </div>
            <% if can? :destroy, recipe_food.food %>
              <div>
                <%= button_to 'Remove', method: :delete, class: "btn btn-danger" %>
              </div>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>