config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shopping_lists

  resources :foods, only: %i[index new create show destroy]
  resources :users, only: %i[index new create show destroy]
  resources :recipes, only: %i[index new create show destroy] do
    resources :recipes_foods, only: %i[new create]
  end

  root 'users#index'
  get '/public_recipes', to: 'public_recipes#index'
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipes_foods
  has_many :recipes, through: :recipes_foods
  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :user_id, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1, only_integer: true }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # POST /foods or /foods.json
  def create
    user = current_user
    @food = Food.new(food_params)
    @food.user = user

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    food = Food.find_by(id: params[:id])
    if food.present?
      if food.destroy
        flash[:notice] = 'Food was successfully deleted'
      else
        flash[:alert] = 'Food was not deleted, please try again later.'
      end
    else
      flash[:alert] = 'Food was not found, please try again later.'
    end
    redirect_to foods_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/_show.html.erb
<tr>
  <td><%= food.name %></td>
  <td><%= food.measurement_unit %></td>
  <td>$ <%= food.price %></td>
  <td class="del_btn">
    <% if can? :destroy, food %>
      <div>
        <%= button_to 'Remove', food_path(food), method: :delete, class: "btn btn-danger" %>
      </div>
    <% else %>
      <span>No actions</span>
    <% end %>
  </td>
</tr>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>
<button class="btn btn-primary">
<%= link_to "Create New food", new_food_path, style: 'color:white' %>
</button>
<h1>Foods</h1>
<div id="foods">
  <table class="table">     
    <thead class="table-container">
      <th scope="col">Foods</th>
      <th scope="col">Measurement unit</th>
      <th scope="col">Unit price</th>
      <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% if !@foods.empty? %>
        <% @foods.each do |food| %>
            <%= render 'show', food: food %>
        <% end %>
      <% else %>
        <tr>
          <td colspan="4">No items yet.</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<section class="new-food">
  <h2 class="title text-center">Add New Food</h2>
 <%= form_with(model: @food, url: { action: "create" }) do |form| %>
     <div class="d-flex flex-column align-items-center">
 <div class= "d-flex flex-column align-items-center w-75 mb-3">
      <%= form.text_field :name, autofocus: true, autocomplete: "name", class: "form-control mb-3", Placeholder: "Name"%>
   
      <%= form.text_field :measurement_unit, autofocus: true, autocomplete: "measurement_unit", class: "form-control mb-3", Placeholder: "Measurement unit" %>

      <%= form.number_field :price, step: 0.5, class: "form-control",Placeholder: "Price" %>
 
    <%= form.submit "Add new food", class: "submit-btn", class:'btn btn-primary my-3' %>
    </div>
    </div>
  <% end %> 
</section>