config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shopping_lists

  resources :foods, only: %i[index new create show destroy]
  resources :users, only: %i[index new create show destroy]
  resources :recipes, only: %i[index new create show destroy] do
    resources :recipes_foods, only: %i[new create]
  end

  root 'users#index'
  get '/public_recipes', to: 'public_recipes#index'
end

app/models/recipes_food.rb
class RecipesFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
  validates :food, presence: true
  validates :recipe, presence: true
  validates :quantity, :food_id, presence: true
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }
end

app/models/recipes_foods.rb
class RecipesFoods < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/controllers/recipes_foods_controller.rb
class RecipesFoodsController < ApplicationController
  before_action :set_recipes_food, only: %i[show edit update destroy]

  # GET /recipes_foods or /recipes_foods.json
  def index
    @recipes_foods = RecipesFood.all
  end

  # GET /recipes_foods/1 or /recipes_foods/1.json
  def show; end

  # GET /recipes_foods/new
  def new
    @recipes_food = RecipesFood.new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.where(user_id: current_user.id)
  end

  # POST /recipes_foods or /recipes_foods.json
  def create
    @foods = Food.where(user_id: current_user.id)
    @food = Food.find(recipes_food_params['food'])
    @recipe = Recipe.find(params[:recipe_id])
    @recipes_food = RecipesFood.new(quantity: recipes_food_params['quantity'].to_i, food: @food, recipe: @recipe)

    respond_to do |format|
      if @recipes_food.save
        format.html { redirect_to recipes_path, notice: 'Recipes food was successfully created.' }
        format.json { render :show, status: :created, location: @recipes_foods }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipes_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes_foods/1 or /recipes_foods/1.json
  def destroy
    @recipes_food.destroy

    respond_to do |format|
      format.html { redirect_to recipesFoods_url, notice: 'Recipes food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipes_food
    @recipes_food = RecipesFood.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipes_food_params
    params.require(:recipes_food).permit(:food, :quantity)
  end
end

app/helpers/recipes_foods_helper.rb
module RecipesFoodsHelper
end

app/views/recipes_foods/_form.html.erb
<%= form_with model: @recipes_food, url: recipe_recipes_foods_path, method: :post do |form| %>
 <div class="d-flex flex-column align-items-center">
 <div class= "d-flex flex-column align-items-center w-75 mb-3">
    <%= form.number_field :quantity, Placeholder: "Quantity", class: "form-control w-75 mb-3" %>
  <%= form.select :food, @foods&.map {|food| [food.name, food.id]}, class: "form-select w-75 mb-3" %>
    <%= form.submit class: "btn btn-primary" %>
  </div>
  </div>
<% end %>

app/views/recipes_foods/_recipes_food.html.erb
<div id="<%= dom_id recipes_food %>">
</div>

app/views/recipes_foods/edit.html.erb
<h1>Editing recipes food</h1>

<%= render "form", recipes_food: @recipes_food %>

<br>

<div>
  <%= link_to "Show this recipes food", @recipes_food %> |
  <%= link_to "Back to recipes foods", recipesFoods_path %>
</div>

app/views/recipes_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes foods</h1>

<div id="recipes_foods">
  <% @recipes_foods.each do |recipes_food| %>
    <%= render recipes_food %>
    <p>
      <%= link_to "Show this recipes food", recipes_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipes food", new_recipesFood_path %>

app/views/recipes_foods/new.html.erb
<h1 class="text-center">New recipes food</h1>

<%= render "form", recipes_food: @recipes_food %>

<br>

app/views/recipes_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipes_food %>

<div>
  <%= link_to "Edit this recipes food", edit_recipesFood_path(@recipes_food) %> |
  <%= link_to "Back to recipes foods", recipesFoods_path %>

  <%= button_to "Destroy this recipes food", @recipes_food, method: :delete %>
</div>