config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shopping_lists

  resources :foods, only: %i[index new create show destroy]
  resources :users, only: %i[index new create show destroy]
  resources :recipes, only: %i[index new create show destroy] do
    resources :recipes_foods, only: %i[new create]
  end

  root 'users#index'
  get '/public_recipes', to: 'public_recipes#index'
end

app/views/layouts/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Recipe App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-between" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex">
        <li class="nav-item">
          <button class="btn btn-dark">
          <div class="d-flex flex-row">
          <%= heroicon "home", options: { class: "nav-i" }  %>
            <%= link_to 'Home', root_path, class: "nav-link" %>
            </div>
          </button>
        </li>
        <li class="nav-item">
          <button class="btn btn-dark">
           <div class="d-flex flex-row">
           <%= heroicon "cake", options: { class: "nav-i" }  %>
            <%= link_to 'Foods', foods_path, class: "nav-link" %>
            </div>
          </button>
        </li>
        <li class="nav-item">
          <button class="btn btn-dark">
           <div class="d-flex flex-row">
           <%= heroicon "beaker", options: { class: "nav-i" }  %>
            <%= link_to 'Recipes', recipes_path, class: "nav-link" %>
            </div>
          </button>
        </li>
        <li class="nav-item">
          <button class="btn btn-dark">
           <div class="d-flex flex-row">
           <%= heroicon "speakerphone", options: { class: "nav-i" }  %>
            <%= link_to 'public Recipes', public_recipes_path, class: "nav-link" %>
            </div>
          </button>
        </li>
        <li class="nav-item">
          <button class="btn btn-dark">
           <div class="d-flex flex-row">
          <%= heroicon "shopping-cart", options: { class: "nav-i" }  %>
            <%= link_to 'Shoping List', shopping_lists_path, class: "nav-link" %>
            </div>
          </button>
        </li>
        <li class="nav-item">
        <button class="btn btn-dark">
         <div class="d-flex flex-row">
          <%= heroicon "user-add", options: { class: "nav-i" }  %>
          <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
          </div>
          </button>
        </li>
        <li class="nav-item">
          <button class="btn btn-dark">
           <div class="d-flex flex-row">
          <%= heroicon "user", options: { class: "nav-i" }  %>
            <%= link_to 'Sign In', user_session_path, class: "nav-link" %>
            </div>
          </button>
        </li>

        <li class="nav-item">
          <button class="btn btn-danger signout">
            <%= link_to 'Sign out', destroy_user_session_path, 'data-turbo-method': :delete, class: "nav-link" %>
          </button>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Recipe App</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container w-100 h-100">
  <br/>
  <%= yield %>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>